# Worksheet 04

Name:  Ke Jin \
UID: U98706721

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

d represents the dimensionality of the data, p represents the order of the Minkowski distance.

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Manhattan distance is the sum of differences between two points in each axis. \
Euclidean distance is the shortest distance between two points, just like measuring the length of the straight line between two points.

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

When p is very large, distance will approach to 1.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No. For example, A(0,0), B(1,0), C(0,1), D(A,B) = D(A,C) = 1 and the D(B,C) = 2^(1/p). When P < 1, D(B,C) > 2 = (D(A,B) + D(A,C)), which is violates the triangle inequality.

e) when would you use cosine similarity over the euclidan distance?

cosine similarity is used when two vector is too close under Euclidan distance.

f) what does the jaccard distance account for that the manhattan distance doesn't?

The jaccard distance accounts for the relative overlap or shared elements between two sets, while the Manhattan distance deal with the absolute differences between coordinates of vercotrs.

#### Part 2

Consider the following two sentences:

In [2]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [3]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [4]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'Bob', 'name', 'Alice', 'my', 'is']
[1, 0, 1, 1, 1, 1]


Let's add a new sentence to our corpus:

In [5]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [7]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['hello', 'Bob', 'name', 'hi', 'Alice', 'Claude', 'my', 'is']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [8]:
v1 = [1 if x in s1 else 0 for x in all_words]
v2 = [1 if x in s2 else 0 for x in all_words]
v3 = [1 if x in s3 else 0 for x in all_words]
print(v1)
print(v2)
print(v3)


[1, 0, 1, 0, 1, 0, 1, 1]
[1, 1, 1, 0, 0, 0, 1, 1]
[0, 0, 1, 1, 0, 1, 1, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [10]:
def manhattan_dis(v1, v2):
    dis = 0
    for i in range(len(v1)):
        dis += abs(v1[i]-v2[i])
    return dis
d_v1_v2 = manhattan_dis(v1,v2)
d_v2_v3 = manhattan_dis(v2,v3)
d_v1_v3 = manhattan_dis(v1,v3)
print(d_v1_v2)
print(d_v2_v3)
print(d_v1_v3)
print("v1 and v2 are the most similar under that distance function.")

2
4
4
v1 and v2 are the most similar under that distance function.


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [15]:
import numpy as np
s1 = "hi Alice"
s2 = "hello Claude"
s3 = "Bob my name is Claude"
s4 = "hi Claude my name is Alice"
s5 = "hello Bob"
corpus = [s1, s2, s3, s4, s5]
all_words = list(set([item for x in corpus for item in x.split()]))
vec_mtx = np.zeros((5, len(all_words)))
for s in range(len(corpus)):
    v = [1 if x in corpus[s] else 0 for x in all_words]
    for col in range(len(all_words)):
        vec_mtx[s,col] = v[col]
print(vec_mtx)

[[0. 0. 0. 1. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0.]]


e) How many rows and columns does this matrix have?

Matrix has 5 rows and 8 columns.

f) When using the Manhattan distance, which two sentences are the most similar?

In [22]:
min_dis = 999
c1 = 0
c2 = 0
for i in range(4):
    for j in range(i+1,5):
        dis = manhattan_dis(vec_mtx[i],vec_mtx[j])
        if dis < min_dis:
            min_dis = dis
            c1 = i
            c2 = j
print("the most silimar sentence are", (c1+1), "and", (c2+1))
        

the most silimar sentence are 2 and 5
